name: Release

on:
  push:
    branches:
      - main

permissions: {}
jobs:
  release:
    permissions:
      contents: write # to create release 
      issues: write # to post issue comments
      pull-requests: write # to create pull request 

    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          always-auth: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          registry-url: https://npm.pkg.github.com

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @react-universal:registry=https://npm.pkg.github.com/
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: yarn --immutable

      - name: Publish package
        run: |
            yarn lerna publish --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}