name: Release

on:
  push:
    branches:
      - main

permissions: {}
jobs:
  release:
    permissions:
      contents: write # to create release 
      issues: write # to post issue comments
      pull-requests: write # to create pull request 

    name: Release
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          always-auth: true
          registry-url: https://npm.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: yarn --immutable  

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @react-universal:registry=https://npm.pkg.github.com/
            //npm.pkg.github.com/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        run: |
            yarn lerna publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}